# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: GitHub CI

on:
  - push
  - pull_request

env:
  default-python: '3.10'

jobs:
  tests:
    name: Call Tests
    uses: ./.github/workflows/Testing.yml@main